export const INDICATOR_OUTPUT = {
  BAND: "band" as const,
  HISTOGRAM: "histogram" as const,
  LINE: "line" as const,
} as const;

export const INDICATOR_TYPE = {
  SMA: "sma",
  EMA: "ema",
  WMA: "wma",
  HMA: "hma",
  VWMA: "vwma",
  VWAP: "vwap",
  SUPER_TREND: "superTrend",
  PARABOLIC_SAR: "parabolicSAR",
  ADX: "adx",
  RSI: "rsi",
  MACD: "macd",
  STOCHASTIC: "stochastic",
  AO: "ao",
  UO: "uo",
  WILLIAMS_R: "williamsR",
  CCI: "cci",
  ROC: "roc",
  MOMENTUM: "momentum",
  TSI: "tsi",
  ZSCORE: "zscore",
  STDDEV: "stddev",
  LIN_REG_SLOPE: "linRegSlope",
  ATRP: "atrp",
  CHOP: "chop",
  EFFICIENCY_RATIO: "efficiencyRatio",
  STC: "stc",
  DVO: "dvo",
  KRI: "kri",
  VZO: "vzo",
  VORTEX: "vortex",
  PPO: "ppo",
  TRIX: "trix",
  STOCH_RSI: "stochRsi",
  VOLUME_OSC: "volumeOsc",
  CHAIKIN_OSC: "chaikinOsc",
  EOM: "eom",
  HIST_VOL: "histVol",
  AROON_OSC: "aroonOsc",
  ATR: "atr",
  OBV: "obv",
  MFI: "mfi",
  PVT: "pvt",
  NVI: "nvi",
  CMF: "cmf",
  AD_LINE: "adLine",
  BOLLINGER_BANDS: "bollingerBands",
  KELTNER_CHANNELS: "keltnerChannels",
  DONCHIAN_CHANNELS: "donchianChannels",
} as const;
