export declare const formatCurrency: (value: number, decimals?: number) => string;
export declare const formatVolume: (volume: number) => string;
export declare const formatPrice: (price: number) => string;
export declare const formatPercent: (value: number, showSign?: boolean) => string;
export declare const formatPercentChange: (value: number) => string;
export declare const formatCompact: (value: number) => string;
export declare const formatUSD: (val: number) => string;
export declare const formatIntlCompact: (val: number) => string;
//# sourceMappingURL=formatters.d.ts.map
