import {
  openSessionTool,
  savePlanVersionTool,
  recordAgentActionTool,
  createStrategyDefinitionTool,
  createStrategyVersionTool,
  createCandlestickRequestTool,
  createDatasetSnapshotTool,
  startBacktestRunTool,
  appendResearchNoteTool,
  createArtifactTool,
  getRunSummaryTool,
  discoverMarketsTool,
  getCandlesTool,
  inspectCandleCoverageTool,
  explainDataSourcePolicyTool,
  ensureCandleCoverageTool,
} from "./tools";

export const ALL_TOOLS = [
  openSessionTool,
  savePlanVersionTool,
  recordAgentActionTool,
  createStrategyDefinitionTool,
  createStrategyVersionTool,
  createCandlestickRequestTool,
  createDatasetSnapshotTool,
  startBacktestRunTool,
  appendResearchNoteTool,
  createArtifactTool,
  getRunSummaryTool,
  discoverMarketsTool,
  getCandlesTool,
  inspectCandleCoverageTool,
  explainDataSourcePolicyTool,
  ensureCandleCoverageTool,
];
