export { ApiServiceTag, ApiServiceLive, type ApiService } from "./api/client";
export { ApiError, NetworkError } from "./api/errors";

export {
  CacheServiceTag,
  CacheServiceLive,
  cachedTopAnalysis,
  cachedAnalysis,
  cachedChartData,
  cachedOverview,
  cachedHeatmap,
  cachedBuybackOverview,
  cachedBuybackDetail,
  cachedOpenInterest,
  cachedFundingRate,
  cachedGlobalMarket,
  cachedDashboardData,
  cachedMarketDepthData,
  cachedMultipleAnalyses,
  invalidateTopAnalysis,
  invalidateAnalysis,
  invalidateChartData,
  invalidateAll,
  refreshAnalysis,
  refreshTopAnalysis,
  getCacheStats,
} from "./cache/effect-cache";

export {
  AppLayer,
  type AppContext,
  getAppRuntime,
  disposeRuntime,
  runEffect,
  runEffectExit,
  forkEffect,
  runEffectWithTimeout,
  runConcurrent,
  runBatched,
  runWithConcurrencyLimit,
  runWithRetry,
  runResilient,
  createFiberController,
  type FiberController,
  createDeferred,
  type DeferredEffect,
  createMemoizedEffect,
  createCachedEffect,
  createCachedEffectWithTTL,
} from "./runtime/effect-runtime";

export {
  useEffectQuery,
  useResilientQuery,
  useEffectInterval,
  useLazyEffectQuery,
  useConcurrentQueries,
  useConcurrentQueriesResilient,
  useEffectExit,
  type QueryState,
  type LazyQueryResult,
  type ResilientQueryOptions,
} from "./runtime/use-effect-query";

export {
  filterBySignal,
  getBuySignals,
  getSellSignals,
  getHoldSignals,
  categorizeSignals,
  categorizeAllSignals,
  getOptimalLongEntries,
  getOptimalShortEntries,
  getOptimalEntries,
  getEntriesByStrength,
  sortByEntryStrength,
  sortByConfidence,
  sortByChange24h,
  sortByRisk,
  sortByVolume,
  sortBuybackByYield,
  filterBuybackByMinYield,
  groupBuybackByCategory,
  createMemoizedCategorizer,
  createMemoizedSorter,
  paginate,
  searchBySymbol,
  filterAnalyses,
  computeMarketStats,
  type SignalType,
  type SortKey,
  type FilterCriteria,
  type PaginationResult,
  type MarketStats,
} from "./utils/effect-memoization";

export { cn } from "./utils/cn";

export {
  formatPrice,
  formatVolume,
  formatCurrency,
  formatPercent,
  formatPercentChange,
  formatCompact,
  formatUSD,
  formatIntlCompact,
} from "./utils/formatters";

export {
  colors,
  getChartColors,
  getCandlestickColors,
  getVolumeColor,
  getHeatmapColor,
  getIndicatorColors,
  isDarkMode,
} from "./utils/colors";
